travis:
  secure:
    BINSTAR_TOKEN: G5HgyHG3dpTC6j0Z5Yu8clCm6HEenn25dw+fUpckb7QkUsdXDeNAXRhg65fZ9dQkwbtCgEnCpQx+1WtkFxtkAtn/MZkHQm9gZ79/Rklg0iVbcnlpymyU9ICxnO0fg6PZmECGBqW0ujZuZRzKW3xrJUSk/ekp4Ep2wT2PZe8h/BQ5lnzSdr/bQ07Ega+oo1KFOexHPS4nTr4Lfui9O4pi0wDd1fItb7S2REKt6dDPMbcTVVolhoWmYj9hS15NsZbOyhmMPfurAVihESi3h0r5tsf/xMBEtqUOHDzP5EoeOntZPPgvgkLcOUxT7kC3F9Em5aOePmniCPlmpMJmieQZ2gHeAPrOQ2H32As+XoQmYt4EEuwwR/YQuWmnykh+xWPgwL5/u8O735turU5/CMibNyF1Pn034Pn40VuaGtrm7xOzXgLZRdIuOPvZ/doC7U0xoeopwh8Y++R+IY5YGxITNgOh2HP2I2b0VEKa/hQZ15C6QCrw7CMNRSG0bX868y4Q9w9Y++1O/RV4WzXJdgw2fBSTEoqo3rsjGAGeYH6bmt1enzG6DOMxBFklCZbifM1G2LfBOCxqTatYHYvMh0tPFM0quHiTpc8KhJu7vK87eZYcTjAKzmZGR9PlIZ/Y0juaxxAztVwCAYvLM2jXLG2EWCrncQlwVSgw9Ln5ZaMzCko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
