travis:
  secure:
    BINSTAR_TOKEN: QoCdaNyPQ7b46UpQhGIGKsY+PmwA0dBmDGxjfFlbnuh4KfXR2EEBnAXBtlDpTeYsKXLj85QWkuQZzHtYrTvNAS0sHcSN+F8WMBpezxFFZJ9gUJ92BLFMIaHOQSEAFu1JS5y4WRnEv5jWAGCk5lp0m8X1PIKocDqiFbIJfvaS9Ft01nA9XyP+tb+yefg72iB8KeUyJwnGm1P6WydVQxR3pkT69i+teDzydphmS2Lo1kxI/+hkZQWMb53nIYCGXo+TSpwzqvSglf7vh/uqIoOrDln2fu0A2YspmYdc7mFb3ep1Zp6cfv//jkSiyzdkdJB4GSIAJuDrjjL6+mupSG7gKOnzskQ07Uzqux1+X4aIu7zYoJxlENYltjIwZQbWQo/qPn+Vxu9y6/3wcL883a4DVnDXbf5P3s78GdCInNMniyTE6BeTyr4kV3H81GR8o/U0EMufEw7LLmnvTM+gelPRwOdHQbeBMZeV5V6knds0/XvrohhnqigDror6fENlYtqf1cYZDvMbGRl4jDBuRm7U1ERMX6Owg8yagg1D7JX98lCIiWjlkGzWVCrt8ffNiJhqmwhd+MED/b8UTSyo2rNABFbrvKAzLkvCyVaEq/w4QB8sTtjosc8jwh7qHdRUhQYlW6Pdt+6UEw3RmAYgtHDi8Y3MI5Fl74yajxUarkp8+c0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
